
spring:
  application.name: Duodome13
  boot:
    admin:
      client:
        url:
          - http://localhost:8080
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        trace: false
        web-allow-other: true

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:test
    username: sa
    password:

management:
  endpoint:
    shutdown:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
      base-path: /actuator
server:
  port: 8081
